version: '3'

services:
  rabbit:
    image: "rabbitmq"
    ports:
      - "5672:5672"
  server:
    build: .
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    volumes:
      - datavolume:/gitsinfo
    depends_on:
      - rabbit
  celery:
    build: .
    command: celery -A gitsinfo worker -l info
    volumes:
      - datavolume:/gitsinfo
    depends_on:
      - rabbit
  celery-beat:
    build: .
    command: celery -A gitsinfo beat -l info
    volumes:
      - datavolume:/gitsinfo
    depends_on:
      - rabbit

volumes:
  datavolume: {}
